[project]
name = "NumericalMethods"
version = "0.1.0"
description = "A collection of numerical methods for analysis and optimization."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jax>=0.9.2",
    "loguru>=0.7.3",
]

[tool.setuptools]
packages = ["NumericalAnalysis", "NumericalOptimization"]
